import { Project } from './types';

// Sample project data
export const projects: Project[] = [
  {
    id: 1,
    title:
      'AI-Powered Student Management System For Nepal Enhancing Nepal Ed-Tech',
    description:
      'A comprehensive web application that uses machine learning to predict student performance and provide personalized recommendations. A comprehensive web application that uses machine learning to predict student performance and provide personalized recommendations.',
    author: 'John Smith',
    department: 'Computer Science',
    batch: '2024',
    category: 'Web Development',
    level: 'Undergraduate',
    rating: 4.8,
    slug: 'web-development',
    views: 1250,
    downloads: 89,
    date: '2024-03-15',
    tags: ['React', 'Python', 'Machine Learning', 'MongoDB'],
  },
  {
    id: 2,
    title: 'Smart Home IoT Controller',
    description:
      'An IoT-based home automation system with mobile app control and voice commands integration.',
    author: 'Sarah Johnson',
    department: 'Electrical Engineering',
    batch: '2024',
    category: 'IoT',
    level: 'Graduate',
    rating: 4.6,
    slug: 'web-development',
    views: 980,
    downloads: 67,
    date: '2024-03-10',
    tags: ['Arduino', 'React Native', 'Firebase', 'IoT'],
  },
  {
    id: 3,
    title: 'E-commerce Analytics Dashboard',
    description:
      'Real-time analytics dashboard for e-commerce businesses with predictive sales forecasting.',
    author: 'Mike Chen',
    department: 'Business Administration',
    batch: '2023',
    category: 'Data Science',
    level: 'Graduate',
    rating: 4.7,
    slug: 'web-development',
    views: 1450,
    downloads: 123,
    date: '2024-02-28',
    tags: ['Python', 'Tableau', 'SQL', 'Machine Learning'],
  },
  {
    id: 4,
    title: 'Sustainable Energy Management App',
    description:
      'Mobile application for monitoring and optimizing renewable energy consumption in residential areas.',
    author: 'Emma Wilson',
    department: 'Mechanical Engineering',
    batch: '2024',
    category: 'Mobile App',
    level: 'Undergraduate',
    rating: 4.5,
    slug: 'web-development',
    views: 756,
    downloads: 45,
    date: '2024-02-20',
    tags: ['Flutter', 'Firebase', 'Charts', 'Sustainability'],
  },
  {
    id: 5,
    title: 'Blockchain-Based Voting System',
    description:
      'Secure and transparent voting system using blockchain technology with voter verification.',
    author: 'David Brown',
    department: 'Computer Science',
    batch: '2023',
    category: 'Web Development',
    level: 'Graduate',
    rating: 4.9,
    views: 2100,
    slug: 'web-development',
    downloads: 156,
    date: '2024-01-15',
    tags: ['Blockchain', 'Solidity', 'React', 'Web3'],
  },
  {
    id: 6,
    title: 'Medical Image Analysis Using Deep Learning',
    description:
      'AI system for automated detection of anomalies in medical imaging with high accuracy.',
    author: 'Lisa Garcia',
    department: 'Computer Science',
    batch: '2024',
    category: 'Machine Learning',
    level: 'PhD',
    slug: 'web-development',
    rating: 4.8,
    views: 1800,
    downloads: 201,
    date: '2024-01-10',
    tags: ['TensorFlow', 'Python', 'Medical AI', 'Deep Learning'],
  },
  {
    id: 7,
    title: 'Autonomous Drone Navigation System',
    description:
      'Computer vision-based navigation system for autonomous drones with obstacle avoidance.',
    author: 'Alex Rodriguez',
    department: 'Electrical Engineering',
    batch: '2023',
    category: 'Robotics',
    level: 'Graduate',
    rating: 4.6,
    slug: 'web-development',

    views: 1320,
    downloads: 78,
    date: '2023-12-20',
    tags: ['OpenCV', 'Python', 'Robotics', 'Computer Vision'],
  },
  {
    id: 8,
    title: 'Financial Portfolio Optimizer',
    description:
      'Machine learning-based tool for optimizing investment portfolios with risk assessment.',
    author: 'Jennifer Lee',
    department: 'Business Administration',
    batch: '2024',
    category: 'Data Science',
    level: 'Graduate',
    rating: 4.7,
    views: 1150,
    downloads: 92,
    date: '2023-12-15',
    slug: 'web-development',

    tags: ['Python', 'Pandas', 'Finance', 'Optimization'],
  },
  {
    id: 9,
    title: 'Smart Traffic Management System',
    description:
      'IoT-based traffic monitoring and management system for urban areas with real-time optimization.',
    author: 'Robert Kim',
    department: 'Civil Engineering',
    batch: '2023',
    slug: 'web-development',

    category: 'IoT',
    level: 'Undergraduate',
    rating: 4.4,
    views: 890,
    downloads: 56,
    date: '2023-11-30',
    tags: ['IoT', 'Python', 'Traffic', 'Smart City'],
  },
  {
    id: 10,
    title: 'Virtual Reality Learning Platform',
    description:
      'Immersive VR platform for educational content delivery with interactive 3D environments.',
    author: 'Maria Santos',
    department: 'Design',
    batch: '2024',
    slug: 'web-development',

    category: 'Design Project',
    level: 'Graduate',
    rating: 4.8,
    views: 1650,
    downloads: 134,
    date: '2023-11-25',
    tags: ['Unity', 'VR', 'Education', '3D Modeling'],
  },
  {
    id: 11,
    title: 'Cryptocurrency Trading Bot',
    description:
      'Automated trading bot with machine learning algorithms for cryptocurrency market analysis.',
    author: 'Thomas Anderson',
    department: 'Computer Science',
    batch: '2023',
    category: 'Machine Learning',
    level: 'Undergraduate',
    rating: 4.5,
    views: 2200,
    slug: 'web-development',

    downloads: 187,
    date: '2023-11-10',
    tags: ['Python', 'API', 'Trading', 'Machine Learning'],
  },
  {
    id: 12,
    title: 'Green Building Energy Simulator',
    description:
      'Simulation tool for analyzing energy efficiency in sustainable building designs.',
    author: 'Anna Petrov',
    department: 'Civil Engineering',
    batch: '2024',
    category: 'Research Paper',
    level: 'PhD',
    rating: 4.6,
    views: 1100,
    downloads: 89,
    date: '2023-10-28',
    slug: 'web-development',
    tags: ['Simulation', 'Sustainability', 'Energy', 'Building'],
  },
];

export const batches = [
  '2024',
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
];
export const departments = [
  'Computer Science',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Business Administration',
  'Design',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
];
export const categories = [
  'Web Development',
  'Mobile App',
  'Machine Learning',
  'Data Science',
  'IoT',
  'Robotics',
  'Research Paper',
  'Business Plan',
  'Design Project',
  'Hardware Project',
];
export const levels = ['Undergraduate', 'Graduate', 'PhD', 'Diploma'];
export const sortOptions = [
  { value: 'date', label: 'Date Created' },
  { value: 'title', label: 'Project Title' },
  { value: 'author', label: 'Author Name' },
  { value: 'department', label: 'Department' },
  { value: 'rating', label: 'Rating' },
  { value: 'views', label: 'Views' },
];
